import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'preface',
    'intro',
    {
      type: 'category',
      label: 'Overview',
      items: [
        'why-physical-ai-matters',
        'learning-outcomes',
        'hardware-requirements',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'category',
          label: 'Module 1: ROS 2',
          items: [{ type: 'autogenerated', dirName: '01-ros2-robot-operating-system' }],
        },
        {
          type: 'category',
          label: 'Module 2: Digital Twin',
          items: [{ type: 'autogenerated', dirName: '02-digital-twin-simulation' }],
        },
        {
          type: 'category',
          label: 'Module 3: NVIDIA Isaac',
          items: [{ type: 'autogenerated', dirName: '03-nvidia-isaac-platform' }],
        },
        {
          type: 'category',
          label: 'Module 4: VLA',
          items: [{ type: 'autogenerated', dirName: '04-vision-language-action' }],
        },
      ],
    },
    'assessments',
  ],
};

export default sidebars;
