import React, { useState, useEffect } from 'react';
import clsx from 'clsx';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

// Define the Summary interface matching the API response
interface SummaryData {
  summary: string;
  key_takeaways: string[];
}

interface SummaryTabProps {
  slug: string; // The unique identifier for the lesson (e.g., '01-ros2/fundamentals')
}

export default function SummaryTab({ slug }: SummaryTabProps) {
  const { siteConfig } = useDocusaurusContext();
  
  // Dynamic API URL Construction
  let baseUrl = (siteConfig.customFields?.apiUrl as string) || 'http://localhost:8000';
  if (!baseUrl.startsWith('http://') && !baseUrl.startsWith('https://')) {
    baseUrl = `https://${baseUrl}`;
  }
  const cleanBaseUrl = baseUrl.replace(/\/$/, '');
  const apiUrl = `${cleanBaseUrl}/api/features/summary`;

  const [data, setData] = useState<SummaryData | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    // Only fetch when the tab is mounted (which usually happens when active)
    // However, we want to be careful about re-fetching.
    // A simple way is to fetch on mount.
    
    const fetchSummary = async () => {
      if (!slug) return;
      
      setLoading(true);
      setError(null);
      
      try {
        const response = await fetch(`${apiUrl}?slug=${encodeURIComponent(slug)}`);
        
        if (!response.ok) {
          throw new Error(`Error: ${response.statusText}`);
        }
        
        const result: SummaryData = await response.json();
        setData(result);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to load summary');
      } finally {
        setLoading(false);
      }
    };

    fetchSummary();
  }, [slug, apiUrl]);

  if (loading) {
    return (
      <div className="alert alert--info margin-bottom--md">
        <div className="text--center">
          <strong>Generating AI Summary...</strong>
          <div className="margin-top--sm spinner-border" role="status"></div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="alert alert--danger margin-bottom--md">
        <strong>Failed to load summary.</strong> {error}
        <button 
            className="button button--sm button--primary margin-left--md"
            onClick={() => window.location.reload()}
        >
            Retry
        </button>
      </div>
    );
  }

  if (!data) {
    return null; 
  }

  return (
    <div className="alert alert--success margin-bottom--md">
      <h3>📝 Lesson Summary</h3>
      <p>{data.summary}</p>
      
      <hr style={{borderColor: 'var(--ifm-alert-border-color)'}}/>
      
      <h4>Key Takeaways:</h4>
      <ul>
        {data.key_takeaways.map((point, index) => (
          <li key={index}>{point}</li>
        ))}
      </ul>
      <div className="text--right text--sm text--secondary">
        Generated by AI
      </div>
    </div>
  );
}
